week-1 assignment-1 submission
pesto-students/p13-nishant-naithani-samarthkathal pull request #2
Opened 2023-08-05 15:41 UTC by samarthkathal

2023-08-07 15:58 UTC, NishantNaithani commented
@samarthkathal ,

Full assignment is not updated please have a look.

thanks

2023-08-07 20:06 UTC, samarthkathal commented
I have updated the PR @NishantNaithani 
Please have a look, thanks.

2023-08-08 16:11 UTC, NishantNaithani commented
@samarthkathal 
Added comments, please have a look.

2023-08-08 16:15 UTC, NishantNaithani requested changes

2023-08-08 16:15 UTC, NishantNaithani commented on Week-1/assignmant-2/hometown/index.html
Here always wrap your webpage content under a parent tag,
For e.g. `<main><p>......</p></main>`

2023-08-08 16:15 UTC, NishantNaithani commented on Week-1/assignmant-2/html-tables/index.html
Here `<p></p>` tag is meant for other types of data but here you wrapped `<table></table>` under the `<p></p>` tag, which violates the semantic HTML concept.

2023-08-08 16:15 UTC, NishantNaithani commented on Week-1/assignmant-2/news-articles/index.html
Here `required` attribute for `Name` and `Email` is not used.

2023-08-08 16:15 UTC, NishantNaithani commented on Week-1/assignmant-2/poem/index.html
Here always wrap your webpage content under a parent tag,
For e.g. `<main><p>......</p></main>`

2023-08-09 20:51 UTC, samarthkathal commented
Thanks @NishantNaithani , I've Updated the branch with the suggested changes. Please have a look

2023-08-10 05:25 UTC, NishantNaithani approved these changes

2023-08-10 05:25 UTC, NishantNaithani commented on Week-1/assignmant-2/html-tables/index.html
Here always wrap your webpage content under a parent tag,
For e.g. `<main><p>......</p></main>`

2023-08-10 05:25 UTC, NishantNaithani commented
@samarthkathal ,
Added a small comment

Thanks

2023-08-10 10:14 UTC, NishantNaithani requested changes

2023-08-10 10:14 UTC, NishantNaithani commented on Week-1/assignmant-2/html-tables/index.html
Here always wrap your webpage content under a parent tag,
For e.g. `<main><p>......</p></main>`

2023-08-10 10:20 UTC, samarthkathal commented on Week-1/assignmant-2/html-tables/index.html
fixed it now, thanks

2023-08-10 10:21 UTC, samarthkathal commented
@NishantNaithani I've added the `<main>` tag now, please check
thanks

2023-08-10 10:22 UTC, NishantNaithani approved these changes

2023-08-13 06:59 UTC, NishantNaithani approved these changes

2023-08-14 18:32 UTC, merged